version: '3.8'
services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: minibanco
    ports:
      - "5432:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

  api:
    build: .
    restart: always
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: senha123
      DB_NAME: minibanco
      DB_PORT: 5432
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - postgres
