services:
  postgres:
    image: postgres:17
    container_name: minibanco-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: minibanco
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - openfinance_network

volumes:
  postgres_data:

networks:
  openfinance_network:
    driver: bridge
